# Generated by Django 4.2 on 2023-04-16 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrations', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrations.speciality'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrations.status'),
        ),
    ]
