# Generated by Django 4.2 on 2023-07-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('type_document', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('eps', models.CharField(blank=True, max_length=50)),
                ('date_cite', models.DateField(blank=True, null=True)),
                ('hour_cite', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrations.doctor')),
            ],
        ),
    ]
