# Generated by Django 4.2 on 2023-04-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrations', '0001_initial'),
        ('pattients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('type_document', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('date_cite', models.DateField(blank=True, null=True)),
                ('hour_cite', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrations.doctor')),
                ('id_pattient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattients.pattient')),
                ('id_speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrations.speciality')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrations.status')),
            ],
        ),
    ]
