# Generated by Django 4.2 on 2023-04-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cites',
            name='eps',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cites',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
