# Generated by Django 4.2 on 2023-07-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cites',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
