# Generated by Django 4.2 on 2023-05-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0002_cites_eps_cites_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cites',
            name='document',
            field=models.CharField(max_length=20),
        ),
    ]
