# Generated by Django 4.2 on 2023-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='eps',
            field=models.CharField(default='convida', max_length=50),
        ),
        migrations.AddField(
            model_name='pattient',
            name='eps',
            field=models.CharField(default='Convida', max_length=50),
        ),
    ]
