# Generated by Django 4.2 on 2023-07-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattients', '0003_rename_id_pattient_family_pattient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
