# Generated by Django 4.2 on 2023-04-16 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 16, 23, 8, 41, 294018, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 16, 23, 8, 52, 233261, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
